# fly.toml app configuration file generated for feeds on 2023-05-23T19:11:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feeds"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
